### ISSUE TITLE
No Modal

### ISSUE THREAD

**Issue by colecmc** [chrisdavies/tiny-date-picker#1]
Tiny-Date-Picker is awesome. Simple and light weight. Can it be used without a modal, so the calendar is always visible on the page? How should this be done?

**Comment by chrisdavies** [comment]
Thanks! It wasn't designed with that use-case in mind, and right now it removes the calendar from the DOM whenever hide is invoked. I don't think there's a good workaround, either, unfortunately. When I have a chance, I can look into what it might take to make that happen. I don't imagine it would require a whole lot of changes to the code.

**Comment by colecmc** [comment]
Great! Your module is super compact (292 lines) which is amazing! Perhaps I could submit a pull request.

**Comment by chrisdavies** [comment]
Sure! That'd be more than welcome.

**Comment by chrisdavies** [comment]
I'm going to close this as it hasn't had any action in a while. Definitely feel free to send a PR when you want!

**Comment by colecmc** [comment]
Yes, I hope to get to it soon. Priorities have just shifted a bit.

Thanks,
Calvin
