### ISSUE TITLE
Setting max date to today or date in the past makes `reset` button unusable

### ISSUE THREAD

**Issue by nerdgore** [chrisdavies/tiny-date-picker#13]
Using the `max` setting to always set the date to today or any date in the past, i.e. `max: new Date()` makes the `reset` button unusable.

At least for the today case I tracked this down to be a bug in the `inRange` method. There, if no date is given, `Date.now()` is used and compared to the max Date which is always the day at 0:00am. Which means `Date.now()` is always out of range in this case.

This could be fixed by either setting `maxStamp` to 23:59:59 or instead of using `Date.now()` parsing the current day the same as min and max values.

Behaviour is the same for past dates, But I guess the fix is a bit more complicated.

**Comment by chrisdavies** [comment]
Good find! Thanks. I fixed it in the latest push. Should be live now.
