### ISSUE TITLE
Selected day is also highlighted in other months

### ISSUE THREAD

**Issue by nerdgore** [chrisdavies/tiny-date-picker#14]
__Actual__
If I select a date in the picker and then reopen it again, moving to a different month shows the same day selected.

__Expected__
If I change the view to another month and the selected day is not visible, then no day is selected.

__Steps to reproduce__

1. Open date picker
1. Select August 30th
1. Open date picker again
1. Change month to September
1. September 30th is selected

**Comment by chrisdavies** [comment]
That's by design. This is heavily based on:

http://amsul.ca/pickadate.js/

And was, in fact a substitution for pickadate on a project I have that doesn't use jQuery.

**Comment by nerdgore** [comment]
I understand the motivation and design decision. However I would still consider this a bug. Since tiny-date-picker does not differentiate between selected and highlighted date. Since by design it is possible that the date textfield is not visible, it gets confusing if the selected day is visible when switching to an adjacent month.

pickadate.js
<img width="753" alt="screen shot 2016-08-31 at 09 22 33" src="https://cloud.githubusercontent.com/assets/1582533/18119810/c17b4506-6f5c-11e6-925b-6c5b9cdac976.png">

tiny-date-picker (with custom styles)
![screen shot 2016-08-31 at 09 25 38](https://cloud.githubusercontent.com/assets/1582533/18119841/ebac4410-6f5c-11e6-8fd6-2984ab0065da.png)

In both instances I selected August 31 and reopened the date picker changing month to September.

**Comment by chrisdavies** [comment]
Hm. The reason it works this way is that the selected item is how we keep focus on the calendar and enable keyboard navigation (up/down, etc).  We could split this into two states (e.g. focused-date vs current-value). 

So, there would always be a focused-date visible, but the current-value would be separate.

Thoughts?

**Comment by chrisdavies** [comment]
Should be working now. See the demo: http://chrisdavies.github.io/tiny-date-picker/

Thanks for insisting on this. :) I misunderstood you at first.

**Comment by nerdgore** [comment]
Great, that's much better.
