### ISSUE TITLE
max date is pre filled in input

### ISSUE THREAD

**Issue by nerdgore** [chrisdavies/tiny-date-picker#17]
It looks like there is a small issue with min and max dates. If The date field is not populated I would expect it to stay empty even though currentDate is out of range.

It seems like the issue is on line 18. I would try fixing it but I am tied up with other projects unfortunately.

**Actual behaviour:**
Given the date filed has no input value
When a max date is defined
Then the max date is used as input value

**Expected behaviour:**
Given the date filed has no input value
When a max date is defined
Then the date field stays empty

**Comment by chrisdavies** [comment]
Thanks! I was out on vacation, so didn't get around to this until now. 

Should be fixed in the latest change.
