### ISSUE TITLE
Please add year and month selection option

### ISSUE THREAD

**Issue by martonx** [chrisdavies/tiny-date-picker#20]
Hi,

First of all this lib is a very good little js gem. But please add year and month picking option to it, for example if I would like to use it for birthdays. Here it is an example: http://dbushell.github.io/Pikaday/

Thank you very much!

**Comment by chrisdavies** [comment]
Yeah. This has been on my todo bucket for a while. I'll prioritize it.

**Comment by chrisdavies** [comment]
Hey. I've been playing with various UX for this, and haven't liked any of them. Do you know of a site or app that does this well? It feels really clunky to use a dropdown for month, and an input for year.

**Comment by El4a** [comment]
I personally prefer the way bootstrap does it
![image](https://cloud.githubusercontent.com/assets/15727732/21002717/7e528c1c-bd27-11e6-9137-25b21804a73a.png)
![image](https://cloud.githubusercontent.com/assets/15727732/21002725/8b18aa3a-bd27-11e6-8535-75cf883f9cd8.png)

**Comment by chrisdavies** [comment]
Hey. This provided a really handy reference.

As I mentioned in your other issue, have a look at this preview:

http://chrisdavies.github.io/tiny-date-picker/

See if it meets your needs. I'll be deploying this within the next week. (I just want to get the unit tests working for it.)

**Comment by El4a** [comment]
Ah sweet jezus you are amazing! Looks awesome! :) I still prefer the years to be displayed as tiles instead of dropdown but that's just personal flavor. It definitely fits my need!

**Comment by El4a** [comment]
And maybe as a little extra: it would be nice if the display of the calendar switches to the right date when entering it manually. Right now you need to close it and re-open it to see it change. but that's a minor issue

**Comment by chrisdavies** [comment]
Yeah. I based the behavior of it loosely on the calendars on Airbnb. It's hard to switch the date as you type, because the date is incomplete until you're done typing. And there is no real "done" event other than when the user tabs off of the input field.

What I may do is expose a hook for you to set the date, so you can make the calendar behave however you want as the user types.
