### ISSUE TITLE
Is it possible to attach to multiple inputs of same class?

### ISSUE THREAD

**Issue by skinnyvin** [chrisdavies/tiny-date-picker#21]
Is it possible to attach to multiple inputs of same class? Does not appear so. Ta

**Comment by chrisdavies** [comment]
Yes. Here's an example:

https://jsbin.com/mucoja/edit?output

The relevant code is:

```js
const inputs = Array.prototype.slice.call(document.querySelectorAll('.dt'));

inputs.forEach(TinyDatePicker);
```

Basically, you select all of the inputs you want, and you attach the date picker to each of them.

**Comment by skinnyvin** [comment]
Brilliant. Thank you for the quick response Chris. Appreciated.

**Comment by amy-cheung** [comment]
Would you be able to set and pass options through in the same manner? ie. I want all the datepickers to open below using mode: 'dp-below'... thus I would need something similar to: 

inputs.forEach(TinyDatePicker,{mode: 'dp-below'});

Is this possible?

**Comment by chrisdavies** [comment]
Yep. TinyDatePicker is just a function, so you can call it like any other JS function:

`inputs.forEach(() => TinyDatePicker({mode: 'dp-below'}));`

**Comment by amy-cheung** [comment]
Thanks for the quick response. 

I wasn't able to apply the code you provided as it threw an error for me:
`Uncaught TypeError: el.addEventListener is not a function`

But I was able to get it working using a similar idea.
`const inputs = Array.prototype.slice.call(document.querySelectorAll('.input-datepicker'));
for (var i = 0; i < inputs.length; i++) {
	TinyDatePicker(inputs[i], {
		mode: 'dp-below'
	});
}`

Just posting it here, in case anyone runs into a similar issue.
Thanks!
