### ISSUE TITLE
Please add manual entry of a date

### ISSUE THREAD

**Issue by El4a** [chrisdavies/tiny-date-picker#22]
I would love the option to use the datepicker as a popup and not as a overlay modal, so you can also enter a date manually (preferably with different input formats but without having to use moment). I think it would contribute to overal usability.

**Comment by chrisdavies** [comment]
Have a look at the second input option here: http://chrisdavies.github.io/tiny-date-picker/

It's the next version of this library. There are some breaking changes, so it might be a major version bump.

Let me know if that fits your needs.
