### ISSUE TITLE
Hide or at least disable days not in current month

### ISSUE THREAD

**Issue by Nanstop** [chrisdavies/tiny-date-picker#24]
It would be super helpful if the js can be smart enough to figure out how many extra days from previous/next month is needed to include in current month, 6 from previous month before 1st seems to be not too bad, but 13 days from next month is definitely too much. At least js should be able to tag those not belong to current month so we can do something with the css. 

Thank you and love what you doing, keep it up :)

**Comment by chrisdavies** [comment]
Thanks. I'm glad you like it!

I'm not sure if I understand what you're asking for here. It does currently display days from previous/next months, and they do have a unique class `dp-edge-day` when the picker is showing. The way it computes what days to show is to always have 6 rows. That way, the date picker shows consistently (size and ratios) no matter the month.

**Comment by Nanstop** [comment]
@chrisdavies The issue I am suggesting here is looking at the calendar at any month (i.e. Jan 2017), 6 row may not be the best choice, (Jan of 2017 would be fine with 5 row). We can prevent this extra row in some cases by adding some simply logic (i.e. 1st of this month is Sun, then only 5 row is needed). 

I am not sure if having consistent size and ratios by doing 6 rows calendar will serve the best user experience.

**Comment by chrisdavies** [comment]
I like it because it keeps the calendar's position predictable and all of the buttons in one place. What we could do. What we could do is style add a class to the last row (e.g. 'dp-row-empty' or something) and folks could choose what to do with it (e.g. animate out, or display none, or leave it).

Thoughts?

**Comment by Nanstop** [comment]
Have a unique class added to the last row (only if none of the date belongs to the current month) would be super helpful and flexible for different needs 👍

**Comment by chrisdavies** [comment]
Also, going to punt on this for the reasons mentioned. If you want to push forward with this, the v3 date picker is (slightly) easier to hop into and contribute to... (I hope.) :)
