### ISSUE TITLE
smart positioning

### ISSUE THREAD

**Issue by Nanstop** [chrisdavies/tiny-date-picker#25]
I know there is only "modal" and "below" mode, but "below" is just not good for all the situations, ideally the calendar should be smart about the available space for all directions and position itself properly.

Considering the manual date input is only accommodated by "below" mode calendar, this mode is more desired than modal, because manual input is pretty standard.

Thank you and keep up with the awesome work 👍

**Comment by chrisdavies** [comment]
Yeah. This is on my todo list, for sure. I threw the "below" feature in fairly quickly to solve an immediate problem.

**Comment by Nanstop** [comment]
@chrisdavies Cool man, looking forward to see this enhancement done. The user experience I am picturing is a user can still manually type things while calendar is showing and as soon as it is a valid date (string or obj), the calendar will be able to show the correct date in real time and be smart about its positioning.

**Comment by chrisdavies** [comment]
Yeah. That's not the first request for a live-updating date. I'll add a second issue to track that.

**Comment by chrisdavies** [comment]
Should be fixed in v2.0.4
