### ISSUE TITLE
Shouldn't be able to go back and forth beyond min and max defined

### ISSUE THREAD

**Issue by Nanstop** [chrisdavies/tiny-date-picker#26]
Hi Chris,

This might be a quick fix bug which after I construct a tinyDatePicker (giving max and min as start and end date) I was still able to go back and forth with the left and right arrow to month beyond start/end date.

**Comment by chrisdavies** [comment]
The main reason for this is that you can have an input field with a date outside of the range, and I want to show that date in the datepicker, even though it's not selectable, and the user should be able to navigate from that date to a valid date.

**Comment by Nanstop** [comment]
@chrisdavies that is a valid point you have, I would like to be able to go to any date I typed if I were a user. Maybe we can do something  in the options object or add class to calendars out of range (but then you need to keep track of the range to maintain the class 👎 ) 
Or we can still show any date the user entered but disable the arrows once out of range (I don't think these two things conflict with each other)

**Comment by chrisdavies** [comment]
I think I'm going to leave the behavior as is, unless this is a blocker.
