### ISSUE TITLE
Callback and focus next

### ISSUE THREAD

**Issue by Wyzix33** [chrisdavies/tiny-date-picker#3]
Hi, i love your date picker, use it in 2 projects and some great options you may add to it are:
 - callback  - execute something before, while or after a date is selected
 - focus next - usually in a form after you select a date you must fill some other field, so a focus on the next element after selection will help (this can be a data-type attribute on the element itself)  so  something like this:

`<input type="text" class="date-example" tabindex="400" id="MyDate" data-focus_next="MyOtherField" />
<input type="text" id="MyOtherField"/>`

Good job!

**Comment by chrisdavies** [comment]
Hey. Glad you like it.

I like the idea of a callback (or callbacks). 

I don't tend to use ids in my forms. (Probably should, but using React, I haven't had the need.) If I add a callback: `onDateSelected`, the consumer could fairly easily select the next field...

```js
TinyDatePicker(document.querySelector('input'), {
  onDateSelected: () => document.querySelector('.foo-bar').select()
})
```

Thoughts?

**Comment by Wyzix33** [comment]
Yes, I know that a callback can be used for anything, i was just thinking that for something as trivial as a focus it's faster with a simple custom attribute :)
Thanks

**Comment by chrisdavies** [comment]
I was thinking about this a bit more... Haven't started on it yet due to a bunch of other things going on...

I wonder if you could essentially get away without having callbacks on the date picker object, but instead watch the field it's associated with:

```js
var myInput = document.querySelector('input')
TinyDatePicker(myInput, {
  // ... config stuff ...
})

myInput.addEventListener('focus', function (e) {
   // This is basically a "before show"
})

myInput.addEventListener('change', function (e) {
   // This is basically an "after select"
})
```

It doesn't really cover the `hiding`, `hidden`, and `beforeChange` states, though...

**Comment by Wyzix33** [comment]
Sure :) I didn't think about using the input for that (that solved my problem), better yet, you can add those events as methods so they can be assigned as option parameters for every state
`TinyDatePicker(document.querySelector('input'), {
      onInitialize: function (value) {
           //... do something with value ...
      },
      onChange: function (value) {
          //... do something with value ...
      }, // ... for every state (onInitialize,onChange,onClear,onFocus,onBlur)
`
I just added an event for onmouseover ( I needed to show how many days are between a previously selected date and a hovered day), so you can add even onHover event. 
something like this

`... 
       events: {
	  onInitialize         : null, // function(value) { ... }
	  onChange         : null, // function(value) { ... }
          ...
	},
	setupevents: function() {
			var key, fn, evs = {
				'initialize'      : 'onInitialize',
				'change'       : 'onChange',
				'clear'           : 'onClear',
				'load'            : 'onLoad',
				'focus'          : 'onFocus',
				'blur'            : 'onBlur'
			};
			for (key in evs) {
				if (evs.hasOwnProperty(key)) {
					fn = this.events[evs[key]];
					if (fn) //add event on key  addEventListener(key, fn);
				}
			}
		}, ...`
setupevents();
Not tested
Hope it helps

**Comment by chrisdavies** [comment]
Awesome. Glad to hear it helped. 

Were you able to work around all of your issues? If so, I'll postpone doing these updates... I'm trying to keep the library as small as possible!

I'm about to start integrating it into one of my projects, and that's when I'll do updates.

**Comment by mnasyrov** [comment]
Hello!
I tried to subscribe to 'change' input's event however it seems like not triggered after picking a date.

For a test I appended a following code to the demo page:
```
document.querySelector('input').addEventListener('change', function (e) {
   console.log(document.querySelector('input').value)
})
```

Thanks.

**Comment by chrisdavies** [comment]
Yeah. Good call. Inputs don't fire those events when their values are programmatically manipulated.

If you pull the latest version, you should get a `change` event now in IE9+. It came at the cost of some size, but I think this is the best approach, as it allows for normal form handling and event bubling.

Thanks!
