### ISSUE TITLE
Expose an API so we can edit date, open/close selectors

### ISSUE THREAD

**Issue by alcalyn** [chrisdavies/tiny-date-picker#32]
Once I instanciated a TinyDatePicker, I want to change date or open month menu with JS.

In example, I could do things like:

``` js
let datepicker = TinyDatePicker(element, params);

// Manually updating date
datepicker.setYear(1950);

// Event API
datepicker.onSelectYear(function () {
    // Manually open selectors for year or month
    datepicker.openMonthSelector();
});

datepicker.onSelectDay(function () {
    datepicker.close();
});
```

My first need was to create a birthdate selector, and make it more "fluid".

**Comment by alcalyn** [comment]
Introduced in this PR: https://github.com/chrisdavies/tiny-date-picker/pull/34

**Comment by chrisdavies** [comment]
This should be good to go in the latest release. See the readme for more details. Thanks again for the pull request!
