### ISSUE TITLE
iOS safari

### ISSUE THREAD

**Issue by fzzylogic** [chrisdavies/tiny-date-picker#38]
Hi

Thanks for sharing this fantastic little date picker. Had to make two tiny changes so it would work on iOS 9.35 under Safari.

Issue description:
After clicking on the date input field on stock safari on iOS 9.35 , nothing happens.

Reason:
Appears to be twofold. 
First that this version of Safari doesn't like mousedown, but 'touchend' works.
Second, Safari sets context.inputFocused() asynchronously, so it's still 'indefined' when check by TinyDate, preventing the modal from being displayed.

My workaround was just to check for 'touchend' in both places separately and not bother to check if the element is focused (since tab isn't an issue on most touch devices). Works fine then.

Thanks again for sharing this!

**Comment by chrisdavies** [comment]
Interesting. I'm an Android user, so iOS doesn't get enough love from me.

Would you mind putting a pull-request together? If not, I'll look at getting a patch in this weekend.

Thanks for the heads up!

**Comment by fzzylogic** [comment]
Submitted pull request, thanks.

**Comment by chrisdavies** [comment]
For the record, this conversation is continued here:

https://github.com/chrisdavies/tiny-date-picker/pull/39

**Comment by chrisdavies** [comment]
Closing, per discussion in pull request.
