### ISSUE TITLE
scrollbars appearing after modal activated

### ISSUE THREAD

**Issue by gavynriebau** [chrisdavies/tiny-date-picker#4]
Firstly, tiny-date-picker is awesome, I love how nice it looks and how clean your code is.

The only issue I have with it is that, under the following conditions, activating the picker causes vertical scrollbars to show:

* Use `display: flex` on body element with `flex-direction: column`
* Include a "main" or "content" wrapper with `flex: 1`
* Include a second element (e.g. footer)

I was using the above styling to create a content section with a footer.

Took me some time to figure out exactly how to replicate this so I saved these conditions so you can see what I'm talking about:
 [here](http://gavynriebau.github.io/tiny-date-picker/)
Just click the picker to see the issue (sorry about the butchered styling).

I found this is resolved if line 12 of TinyDatePicker, is changed from:

```
var focusCatcher = htmlToElement('<button style="position: absolute; width: 1; height: 1; overflow: hidden; border: 0; background: transparent;"></button>');
```

to (note the extra `top: 0` inside the style attribute).

```
var focusCatcher = htmlToElement('<button style="position: absolute; width: 1; height: 1; overflow: hidden; border: 0; background: transparent; top: 0;"></button>');
```

**Comment by Wyzix33** [comment]
nice catch :+1:

**Comment by chrisdavies** [comment]
Cool. I wasn't able to repro the problem (in Chrome on Mac), but I merged your fix in. Out of curiosity, what browser/OS were you using?

Thanks for reporting and fixing!

**Comment by gavynriebau** [comment]
@chrisdavies Thanks for merging my fix.

I tested using (both on Linux):

* Chrome 49.0.2623.110
* Firefox 45.0
