### ISSUE TITLE
Events don't work on elements without class

### ISSUE THREAD

**Issue by d-eisenga** [chrisdavies/tiny-date-picker#40]
The `on` function uses the RegExp `/./` which will match any string of at least one character. So if my `<input>` element has no class, the handler function doesn't get called. Changing the default RegExp to `/.?/` does the trick.

**Comment by chrisdavies** [comment]
Gotcha. This is in the scenario where no selector was provided. I think I'll go with `/.*/` which should be a bit more efficient, I think?

**Comment by chrisdavies** [comment]
Fixed in the latest version.

Thanks for finding and reporting this!

**Comment by d-eisenga** [comment]
Thank you!
