### ISSUE TITLE
Provide a way to remove tiny-date-picker from element

### ISSUE THREAD

**Issue by d-eisenga** [chrisdavies/tiny-date-picker#41]
Some sort of `unbind` method on the context, to remove the various event listeners from the input element that get added in the main function, would be a very helpful addition to this library.

**Comment by chrisdavies** [comment]
That's an interesting idea. Most libraries that have an "on" also have an "off", so it makes sense.

Out of curiosity, what's the scenario you're running into where you want to turn it off? I haven't run into that need yet.

**Comment by d-eisenga** [comment]
Ah, sorry for the late reply.

The scenario was that I was working on a Preact wrapper for the date picker, which happens to be displayed inside a modal. Because Preact reuses the `<input>` element when it can, but does call the component's constructor function each time the modal opens, the 'focus' events were getting added multiple times. Being able to remove the date picker functionality from the `<input>` element when the component is unmounted should prevent this (for now I was able to get around it by manually removing the element from its parent upon unmounting, but it's a bit hacky).

**Comment by chrisdavies** [comment]
Ah. Cool. Preact is great! Couldn't you instead track whether or not the
input is being reused and just not re-initialize the date picker?

I imagine preact has a way to know if this is a reuse situation or not.
Maybe componentDidMount or something like that?

**Comment by d-eisenga** [comment]
None that I was able to find. `ComponentDidMount` fires even when the element inside is reused. I considered tracking the `<input>` in the component's state and only calling `TinyDatePicker()` if it's different, but I thought that was equally hacky.

**Comment by chrisdavies** [comment]
Interesting... that's surprising behavior. I think I had a similar issue in
the past, though, now that you mention it, and I ended up creating a
convenience function that would only run once.

**Comment by stalkerg** [comment]
It's important for me too because I making SPA and use data picker inside component and I want to remove data-picker when component call destroy. 
Currently, I just find data picker by class and remove from the body...

**Comment by chrisdavies** [comment]
Added a `destroy` method in v2.4.0 which closes the date picker and removes all event handlers from the associated input.

**Comment by d-eisenga** [comment]
Thank you!

**Comment by stalkerg** [comment]
Not yet.
