### ISSUE TITLE
Disable days?

### ISSUE THREAD

**Issue by Spunkie** [chrisdavies/tiny-date-picker#45]
Is it possible to disable entire days? For example I need to make a datepicker that does not allow weekends so I would want to disable every Saturday/Sunday in TinyDatePicker.

I tried adding `.dp-day-disabled` to the days alongside `.dp-day` but this only changed the styling while still allowing the days to be selected.

**Comment by chrisdavies** [comment]
Not right now, but it would be a minor change, and arguably a better design
for some internal plumbing in the library.

I'll put it together this week.

**Comment by chrisdavies** [comment]
Added. See the readme:

```js
// Customizes what CSS class is associated with a particular date.
  // For example, to disable weekends:
  // dateClass(dt) {
  //   return (dt.getDay() % 6) ? '' : 'dp-day-disabled';
  // }
  dateClass: function (dt, context) {
    // dt is the date
    // context is the datepicker context
  }
```

**Comment by Spunkie** [comment]
I've tried out the new version and it does apply the css correctly to style the days as disabled but nothing actually prevents them from selecting the disabled days. So the disabled days are not really disabled.

<img src="https://i.spunkiedesign.com/3WCbQdr.png">

**Comment by chrisdavies** [comment]
Ah. You're right. I thought I'd tested that, but was mistaken. I'm leaving the dateClass option in, since it seems useful, but I have added an inRange option, too. Again, see the readme. *that* should solve the problem!
