### ISSUE TITLE
Open modal if you back to tab

### ISSUE THREAD

**Issue by stalkerg** [chrisdavies/tiny-date-picker#47]
Currently, if you open and close modal window and change Chrome tab after, focus still keep on input. 
If you back to the tab which contains "date picker", modal view open again because:
```js
on('focus', input, bufferShow);
```
Chrome emit focus for previews focused element during tab activate. 
If "tiny-data-picker" had onClose hook I can be "blur" current focus but, they have not.

**Comment by stalkerg** [comment]
Also, close button not working under iPad emulation in Chrome. 
```js
returnFocusFromModal
```
maybe it's should be a common behavior.

**Comment by chrisdavies** [comment]
Unfortunately, the behavior of the modal showing when you re-focus the browser tab is probably impossible to avoid without giving up on another feature that I think is more important (which is keeping tab-focus on the right control).

I do think we should have an `onClose` hook, though. I'm going to add that as a separate issue and close this one.

**Comment by stalkerg** [comment]
> which is keeping tab-focus on the right control

Can you explain why it is important?

**Comment by chrisdavies** [comment]
Because the typical flow (in my experience) for filling out a form is to go in tab-order through it. When you're done selecting your date, the field should still have focus, so you can tab to the next field.

**Comment by stalkerg** [comment]
In my case, I am using date-picket not in "form" but just as a widget on each page. It's mean you shouldn't and can't use a keyboard to choose the field. 
Anyway, I think this case should be just configured (as option).

**Comment by stalkerg** [comment]
Ok, what about the special parameter or onClose hook?
