### ISSUE TITLE
Pass an array of dates to be highlighted in the calendar.

### ISSUE THREAD

**Issue by jackiboy** [chrisdavies/tiny-date-picker#50]
Hi.

I am using Tiny Date Picker inside an events booking form. Is it possible to pass an array of dates that can be displayed inside the calendar (with the date being highlighted).

The reason I want to do this is so the customer knows the venue is booked on that certain date.

Thanks

**Comment by chrisdavies** [comment]
No, it's not possible right now, but you can specify an arbitrary set of
dates that are disabled. (Via the inRange option).

You can also specify custom CSS classes for any dates using the options as
well.
