### ISSUE TITLE
Not an issue. Merely a suggestion.

### ISSUE THREAD

**Issue by frdnrdb** [chrisdavies/tiny-date-picker#51]
Are you considering adding range-functionality? In my opinion this is the cleanest/ most effective approach: http://longbill.github.io/jquery-date-range-picker. It's similar to Bootstrap's and jQuery UI's sollutions, but it's snappier. The downside: It's jQuery dependent.

This guy made a pure JS variant of the afforementioned range-pickers, but it's a bit too much: http://lopezb.com/hoteldatepicker/

Anyway. If your tiny vanilla JS picker gets a snappy range functionality it will definitely be my go-to picker in the future ;-) 

Good work!

**Comment by chrisdavies** [comment]
This isn't a core use case for this library (for me). But I think I could fairly easily build that functionality on top of this lib.

I think I'd prefer it to bind to two different input fields, rather than putting the date range into a single input field the way hoteldatepicker does.

Anyway, interesting suggestion. I'll leave this open until I have time to attempt it.

**Comment by chrisdavies** [comment]
I had a chance to take a stab at this today.

Here's the demo: http://christophilus.com/tiny-date-picker/date-range.html

And here are the docs: https://github.com/chrisdavies/tiny-date-picker/blob/master/docs/date-range-picker.md

I kept it super minimal.

**Comment by frdnrdb** [comment]
wow! that was quick! 
i'll keep my word; your picker is hereby my defdault choice.
... and i'll spread the word :-)

**Comment by chrisdavies** [comment]
Ha. Well, the range is definitely in alpha. I still need to do a few things:

- Allow pass-through of the underlying date picker options
- You currently have to roll your own container and control the show/hide/position of that container. This is not a bad thing, but I might want to at least have one functional out-of-the box container.
- Documentation
