### ISSUE TITLE
Error using pattern atribute

### ISSUE THREAD

**Issue by subversivo58** [chrisdavies/tiny-date-picker#56]
I'm using the "pattern" attribute on an but form whenever I try to submit the form it selects the field again by reopening the modal.

The output was tested against the "pattern" and this ok reopen the modal and consequently does not send.

The "pattern":
```html
<input id="birthday-form-input" type="text" pattern="/^([\d]{4})\/([\d]{2})\/([\d]{2})$/">
```

Example of output from Tiny Date Picker:

    '1999/12/10'

Test in `javascript`:

```javascript
/^([\d]{4})\/([\d]{2})\/([\d]{2})$/.test('1999/12/10') // output: true
```

Complete custom options on Tiny Date Picker instance:
```javascript
let inputDate = document.getElementById('birthday-form-input');
let datePicker = TinyDatePicker(inputDate, {
    format (dt) {
        return dt.getFullYear() + '/' + (dt.getMonth() + 1) + '/' + dt.getDate();
    },
    parse (dt) {
        if ( !dt ) {
            return new Date();
        }
        const [year, month, day] = dt.split('/').map((s) => parseInt(s, 10));
        const result = new Date();
        result.setYear(year);
        result.setMonth(month);
        result.setDate(day);
        return result;
    },
    max: (function() {
        let date = new Date();
        date.setFullYear(date.getFullYear() -18);
        return ( (date.getFullYear()) + '/' + (date.getMonth() ) + '/' + (date.getDate()) );
    })()
})
```

How to fix this?

**Comment by chrisdavies** [comment]
Hm. I've got my hands full at the moment with other work, but my guess is that the input is gaining focus (which shows the modal). One thing you could probably do is disable the field on form submit and then re-enable it when the form submit fails / succeeds. That should prevent it from gaining focus.

**Comment by chrisdavies** [comment]
Hm. Just ran it.

```html
<input id="birthday-form-input" type="text" pattern="^([\d]{4})\/([\d]{,2})\/([\d]{,2})$">
```

Your regex is failing. The above snippet works properly. Note, the `{,2}` instead of `{2}`. Dates like `2017/2/3` would fail your original regex. If you want these dates to always be padded, your format function needs to pad them (e.g. `2017/02/03`)

**Comment by subversivo58** [comment]
Yes indeed, your regex resolves to the extent that it accepts from one to two digits. I am using a two digit regex because it is visually more semantic outside (or beyond) the English language.

I paid more attention to your comment on the return of **months and days of a single digit** so I modified the return of the `format()` function...

```javascript
return dt.getFullYear() + '/' + (('0' + (dt.getMonth() + 1)).slice(-2)) + '/' + (('0' + dt.getDate()).slice(-2));
```

It was not necessary to disable the field to avoid the focus event because of the regex used in pattern.

Thank you for your attention helped me a lot to understand the issue better.

-------
PS: I really enjoyed this library and your comment did not look grumpy. Thanks :smile:
