### ISSUE TITLE
Time entry only , no AM or PM

### ISSUE THREAD

**Issue by weedkiller** [chrisdavies/tiny-date-picker#58]
Hi, I have user who just want to **enter amount of time worked only, i.e. no AM or PM**, i.e. how long and not when for 8HRs, or 14 hrs etc.

I was unable to disable the AM & PM text, can you please share the setting/example to disable it.

Also 

- [ ] how to show default hours: for e.g. on select box, `default to 08:00 hrs.` no AM or PM
- [ ] Different color for HH:MM hours (Blue) and Mins (green)
- [ ] show a button to fill `https://github.com/kbwood/timeentry/blob/master/jquery.timeentry.js`
![image](https://user-images.githubusercontent.com/21086190/34395645-00141932-eb30-11e7-9288-dc1586832120.png)

thanks

**Comment by chrisdavies** [comment]
Hm. Are you sure you're using this library? This library doesn't support time-picking at all: only dates.

**Comment by weedkiller** [comment]
I was asking if you would consider supporting time as well

**Comment by chrisdavies** [comment]
Ah. Gotcha! That wasn't clear to me before, sorry!

I have debated adding an optional time picker, but I haven't done it because personally, I haven't liked any time picking UI I've ever seen. Do you have any examples of good time-picking UIs?

**Comment by weedkiller** [comment]
There are quite a few, but the simplicity of time entry is lost. One package that does both time/date would be great

[Some images](http://bit.ly/2CqrNSn)

[Without IOS](http://bit.ly/2lWNVxc)

![image](https://user-images.githubusercontent.com/21086190/34588262-01e831b2-f17a-11e7-9521-331fd840c105.png)

**Comment by gety9** [comment]
1 vote not to do include it in library.

Majority of people need date picker only (not time)
Why make the library bigger/heavier?

If you would decide to go that route, than it will be better to have separate plugin.

**Comment by chrisdavies** [comment]
@weedkiller I think I agree gety9 about keeping this library focused on dates. I may put a time picker together separately, and maybe pair that library with this one in some way.

Best of luck!
