### ISSUE TITLE
Required CSS Enhancements

### ISSUE THREAD

**Issue by 2rohith2** [chrisdavies/tiny-date-picker#60]
@chrisdavies I like your date picker, but little CSS options required.

1. Allow the developer to specify the color of `current` & `focus` date
![image](https://user-images.githubusercontent.com/5773985/35212691-fb21dc10-ff80-11e7-802c-5502adbfa5f8.png)
I want to use this color `#8253eb` for `current` & `#6931E7` for `focus`

2. Year selection, scrolling to specific year could be done more easily
![image](https://user-images.githubusercontent.com/5773985/35213451-b1e9598a-ff83-11e7-8b1e-8dabddc14af7.png)
Assume I need to select year `1990`, I have to scroll a lot.

You could do something like this
![image](https://user-images.githubusercontent.com/5773985/35213576-1bab9248-ff84-11e7-83f7-a12a215b9bc5.png)
This is from http://bootstrap-datepicker.readthedocs.io/en/latest/

Regards
 @2rohith2

**Comment by chrisdavies** [comment]
I'm glad you like the library!

You should be able to customize all of this yourself with a bit of CSS. If you inspect the calendar, you'll see a bunch of `dp-` class names. I think the two you want to play with are: `dp-current dp-selected`.

I'm torn about the year suggestion. I personally find it more annoying to have to scan a grid than to scan a linear list, especially from a mac or a phone where scrolling quickly is really easy. That said, if you want to arrange the years the way you suggested, you should be able to do it fairly easily by overriding the CSS.

Here's a rough hack (I spent 0 time on). But you could make this look reasonable with some tweaks or by using flexbox:

```css
.dp-year {
    display: inline-block;
    width: 30%;
}
```

**Comment by 2rohith2** [comment]
> `dp-current dp-selected`

Only those aren't required, anyway I have overridden the css properties according to my requirements.

Anyway thanks for wonderful data picker :+1:

**Comment by chrisdavies** [comment]
Hm. Here's a screenshot of what I mean about the years:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/833377/35231595-3cb783ba-ff67-11e7-9682-3cc0ab6a9631.png">

To get that working, I:

- Went here: https://chrisdavies.github.io/tiny-date-picker/
- Clicked on the year on the demo "permanent calendar"
- Right-clicked a year, and did "inspect element" (which opened up dev tools)
- In dev tools, modified the `dp-year` rule to be inline-block and 33% width

So, I know it can be done. I'm not sure what rules are applying to the list in your screenshot, but it looks like your inline-block is being overridden, maybe.
