### ISSUE TITLE
Hover state stays after touch on iOS.

### ISSUE THREAD

**Issue by gety9** [chrisdavies/tiny-date-picker#65]
When pressing next or previous arrows it stays "pressed" after touch.
[SCREENSHOT](https://puu.sh/zsQIH/75d2e55d12.png)

Same behavior on our local site and your demo link.

**Comment by chrisdavies** [comment]
Interesting. It appears to be staying focused once pressed. The focus is *supposed* to return to the highlighted date in the calendar. I'll have a look at it this coming week.

**Comment by chrisdavies** [comment]
Well, haven't had much time lately to dig into things. I'm traveling next week. If you're interested in having a go at it yourself, it's likely to do with how focus is reset after each redraw.

**Comment by chrisdavies** [comment]
Well, this was a lot more of a pain than I expected, but should be fixed in 3.2.1. You need to be sure to get the latest css, too.
