### ISSUE TITLE
Turbolinks issue

### ISSUE THREAD

**Issue by meneerprins** [chrisdavies/tiny-date-picker#70]
With the latest update the href attributes got replaced with '#', now when I click on a date my page gets reloaded because of [Turbolinks](https://github.com/turbolinks/turbolinks). Can this be reverted or maybe changed to a `<button>` instead of `<a>`?

**Comment by chrisdavies** [comment]
Ah. Good ol turbolinks. I'm preventing default on the click event, but it's delegated to the root. Still, I'm surprised that Turbolinks doesn't respect that. 

Your suggested change got cut off by GitHub. Could you resend them, wrapped in backticks?

I could convert the `a` elements to `button` instead or to an Aria span or something.

**Comment by meneerprins** [comment]
Ye 'good ol turbolinks' always causing problems, I edited my post.

**Comment by chrisdavies** [comment]
Ok. I'm in meetings all day, but should be able to get to this tonight. Sorry for the breaking change!

**Comment by meneerprins** [comment]
No worries, not using it in production yet 😃. Thanks for the quick response!

**Comment by chrisdavies** [comment]
I moved from `a` to `button` as you suggested. It's what it should have been all along, logically.

I bumped up to version 2.3, since this might break existing expectations. Anyone moving to 2.3 needs to make sure to update to the latest CSS as well.
