### ISSUE TITLE
Adding a class to the calendar when adjustCalY decides aboveTop or belowTop

### ISSUE THREAD

**Issue by RCopeland** [chrisdavies/tiny-date-picker#71]
This would be helpful for people who want to add a little arrow that points at the input.

**Comment by chrisdavies** [comment]
Good idea. I haven't had much of a chance to work on this library lately, but should have some time this evening or tomorrow.

**Comment by chrisdavies** [comment]
In v3.2.2, I added the classes `dp-is-above` and `dp-is-below` for this scenario. They currently have no actual CSS associated with them. They'll also only show up in browsers that support classList, which is pretty much any browser I care about these days!

**Comment by RCopeland** [comment]
Awesome, thanks!
