### ISSUE TITLE
Manual control of the open/close of the dropdown

### ISSUE THREAD

**Issue by aadjemonkeyrock** [chrisdavies/tiny-date-picker#74]
Is there a way to disable the open on focus? I want to manually control the opening of the dropdown. 

use case: user types the date and only in rare cases wants to use the picker. The picker can then be opened with an additional button.

**Comment by subversivo58** [comment]
Hi @aadjemonkeyrock 

I think a native way would be useful but as I have been using the library for quite some time I have come across this issue.

You can add a listener to your "button" call the plugin by the `<input>` reference and in the `.close()` event clone the `<input>` ... the clone of an object will preserve attributes and children, but will not preserve any changes in the properties of the DOM.

**Example:**

```html
<form>
    <input id="input-target" type="text">
    <button id="open-tdp" type="button">Open Calendar</button>
</form>
```

```javascript
// `<button>` element
let btn = document.getElementById('open-tdp')
// `<button>` Event "click"
btn.addEventListener('click', function(evt) {
    // get `<input>` element
    let input = document.getElementById('input-target')
    // plugin reference
    let dp = TinyDatePicker(input)
    // plugin `.close()` Event
    dp.on('close', () => {
        // clone node
        let clone = input.cloneNode()
        while (input.firstChild) {
            clone.appendChild(input.lastChild)
        }
        input.parentNode.replaceChild(clone, input)
    })
}, false)
```

This solution worked well for me for some time but by using `{once: true}` in the `<button>` event options, it will not work ... I still can not understand why?

Reference of `.cloneNode()`: [Mozila Docs](https://developer.mozilla.org/En/DOM/Node.cloneNode)

**Comment by chrisdavies** [comment]
I think it should be possible w/out having to do a `cloneNode`. I haven't tested this, but something like it should work:

```js
document.querySelector('.my-button').addEventListener('click', () => {
  const input = document.querySelector('.my-input')
  const dp = TinyDatePicker(document.createElement('input'));
  dp.on('select', (_, dp) => input.value = dp.state.selectedDate);
});
```

Note, you probably don't want to set your input value on close, as close will fire regardless of whether or not the user selected anything. The event you want is `select`.

**Comment by chrisdavies** [comment]
@subversivo58 You're right. `open` needs to be called. As for formatting, I'd probably pass it through the same format function that I passed into the date picker's opts. 

```js
document.querySelector('.my-button').addEventListener('click', () => {
  const input = document.querySelector('.my-input', { format: whatevz });
  const dp = TinyDatePicker(document.createElement('input'));
  dp.on('select', (_, dp) => input.value = whatevz(dp.state.selectedDate)).open();
});
```
