### ISSUE TITLE
Disable dates from current date

### ISSUE THREAD

**Issue by dheeraja00** [chrisdavies/tiny-date-picker#75]
Hi,
I am using DateRangePicker & I got the requirement from client that user should not be able to select date after currentdate, so they can only select from previous to today, I can see you have option min & max in tinydatepicker but how can I achieve the required functionality in daterangepicker?

**Comment by chrisdavies** [comment]
Yeap. Someone else recently pointed out that DateRangePicker doesn't actually accept opts. It was on my todo list, and it's in the docs, but the docs are actually wrong.

Here's the issue that tracks this:
https://github.com/chrisdavies/tiny-date-picker/issues/77
