### ISSUE TITLE
Week should start from Monday by ISO_8601

### ISSUE THREAD

**Issue by stalkerg** [chrisdavies/tiny-date-picker#89]
Is it possible to add a special option to use ISO_8601 in the calendar?

**Comment by Dimon24021993** [comment]
You can use 'dayOffset' option in date-piker but i don't understand how to use this option in date-range-picker, it seams not transmitted into render method. If you find a solution - write

**Comment by chrisdavies** [comment]
@Dimon24021993 is right about the `dayOffset` option. It should work for both the DatePicker and the DateRangePicker.

Example:

```js
  const dp = DateRangePicker.DateRangePicker(container, {
    startOpts: {
      dayOffset: 1,
    },
    endOpts: {
      dayOffset: 1,
    },
  })
```

**Comment by stalkerg** [comment]
Thank you! I think will be better to change this options to something more understandable without reading the documentation.
