### ISSUE TITLE
onChooseYear set view to Month

### ISSUE THREAD

**Issue by mouse0270** [chrisdavies/tiny-date-picker#91]
When the `view` is set to `year` the function `onChooseYear` should set the `view` to `month` instead of `day`. 

This would allow the user to select Year > Month > Day where currently they would have to go back up and select `Month` which seems out of order.

**Comment by chrisdavies** [comment]
I think that's only one path. Another path is that the user has clicked "year" in the calendar, selected a year, and then expects to go back to the view that launched the year picker (which is the day view). Left-to-right cultures will click month, then year, based on how they are laid out in the UI currently. But you can control which view is rendered if you want to ensure the order in your scenario.

That said, the month, year (and upcoming time) pickers are going to be dropdowns in v3, if I ever get the time to work on it.
