### ISSUE TITLE
Destroy in PermanentMode is Noop

### ISSUE THREAD

**Issue by cnatis** [chrisdavies/tiny-date-picker#94]
The destroy method in permanent mode is a noop. The end result is even after I have removed the datepicker DOM and destroyed the instance it will continue to listen for events and attempt to open causing errors to be thrown due to undefined and null values.

**Comment by chrisdavies** [comment]
Fixed in the latest release. Thanks for the PR, and sorry for the delay. I've been offline for a while, thanks to a new kiddo. :)
